;BENEMERITA UNIVERSIDAD AUTONOMA DE PUEBLA
;FACULTAD DE CIENCIAS DE LA COMPUTACION
;   MATRICULA | INTEGRANTES
;   201764133 - CHRISTIAN CASTILLO MERINO
;   202089266 - ELTON JOHN QUINTOS ESPINOZA
;   202041509 - JESUS HUERTA AGUILAR
;   202075025 - ALEX ABDIEL RUANO FLORES

;TRABAJO: TABLA ASCII


.MODEL SMALL	    ;DEFINE EL MODELO DE MEMORIA

.DATA			    ;DEFINE EL SEGMENTO DE DATOS
	FILA DB 0       ;SE INICIA FILA EN CERO
    COLU DB 0       ;SE INICIA COLUNMA EN CERO
    
.CODE			    ;DEFINE EL SEGMENTO DE CODIGO


IMPCI MACRO CICLO  ; 
REPETIR:
    PUSH CX     
    PUSH CX
    PUSH CX
    SHR  CL, 4
    
    ;CONVERSION DE HEX A ASCII
    ADD CL, 30H
    CMP CL, 39H
    JLE IMPRIMIR
    ADD CL, 7H
             
             
             
             
    IMPRIMIR:;IMPRIMIR DIGITO (0-F)
        IMPDIGITO CL
        
        POP CX      
        AND CL, 0FH
        
        ADD CL, 30H
        CMP CL, 39H
        JLE IMPRI        ;SALTO A VALORES DE 2 DIGITOS
        ADD CL, 7H       ;VALOR HEXADECIMAL
        
    
    IMPRI:               ;IMPRIMIR 2 DIGITOS
        IMPDIGITO CL     ;LLAMADA IMPRIMIR DIGITO ANTES DEL IGUAL
        CALL IGUAL       ;LLAMADA IMPRIMIR IGUAL
        POP CX        
    
        IMPRICARACTER CX ;LLAMADA IMPRIMIR CARACTER ASCII
        
        CURSOR FILA COLU ;LLAMADA DE MACRO 
        INC FILA         ;REPOSICIONAMIENTO DE CURSOR
        CMP FILA,24    
        JNE CONTINUAR    
        MOV FILA,0     
        ADD COLU,7 
    
    
        
    
CONTINUAR:;DETERMINA CUANDO DEJE DE IMPRIMIR   
    POP CX
    INC CX
    CMP CX,256   
    JE FIN
    JMP REPETIR     
IMPCI ENDM


IMPDIGITO MACRO CL      ;IMPRIMIR NUMERO DEL CARACTER
    MOV AH, 02H   
    MOV DL, CL
    INT 21H
IMPDIGITOO ENDM

IGUAL PROC NEAR         ;IMPRIMIR SIMBOLO IGUAL
    MOV AH, 02H
    MOV DL, ':'
    INT 21H
    RET
IGUAL ENDP

IMPRICARACTER MACRO CX  ;IMPRIMIR CARACTER ASCII
    MOV AH,02H
    MOV DL,CL
    INT 21H
IMPRICARACTER ENDM

CURSOR MACRO FILA COLU  ;POSICIONAMIENTO DE CURSOR
    MOV AH,02H
    MOV DH,FILA    
    MOV DL,COLU    
    INT 10H
CURSOR ENDM
    

INICIO:; MAIN  
    ;INICIALIZACION DE LOS REGISTROS DE SEGMENTO
	MOV AX, @DATA	
	MOV DS, AX		
    MOV CX, 00H  
    
    IMPCI CICLO;DIRIGIR A MACRO PARA IMPRIMIR TODO  

FIN: 
END INICIO  

